evaluacion/config/routes.rb
Rails.application.routes.draw do
 resources :people
end

evaluacion/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

evaluacion/app/models/document.rb
class Document < ApplicationRecord
  has_many :people
end

evaluacion/app/models/person.rb
class Person < ApplicationRecord
    belongs_to :document
    belongs_to :role
end

evaluacion/app/models/role.rb
class Role < ApplicationRecord
  has_many :people
end

evaluacion/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

evaluacion/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def show
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    if @person.destroy
    redirect_to people_path
    else 
       render :new
    end   
  end

  private

  def person_params
    params.require(:person).permit(:identificacion, :primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :document_id, :role_id)
  end
end

evaluacion/app/helpers/application_helper.rb
module ApplicationHelper
end

evaluacion/app/helpers/people_helper.rb
module PeopleHelper
end

evaluacion/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluacion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
  <section class = "row">
    <aside class = "col-md-4">
      <div class="list-group">
        <a href="<%= people_path %>" class="list-group-item list-group-item-action active">Persona</a>
        <a href="<%= new_person_path%>" class="list-group-item list-group-item-action active"> Nueva Persona</a>

      </div>
    </aside>
    <article class = "col-md-8">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </article>
   </section>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  </body>
</html>

evaluacion/app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
    <%= f.input :identificacion %>
    <%= f.input :primer_nombre%>
    <%= f.input :segundo_nombre%>
    <%= f.input :primer_apellido %>
    <%= f.input :segundo_apellido%>
    <%= f.association :document, label_method: :tipo_documento %>
    <%= f.association :role, label_method: :nombre_rol %>
    <%= f.button :submit %>
 <% end %>  

evaluacion/app/views/people/_person.html.erb
<tr>
    <th scope="row"><%= person.id %></th>
    <td><%= person.identificacion%></td>
    <td><%= person.primer_nombre%></td>
    <td><%= person.segundo_nombre%></td>
    <td><%= person.primer_apellido%></td>
    <td><%= person.segundo_apellido%></td>
    <td><%= person.document.tipo_documento%></td>
    <td><%= person.role.nombre_rol%></td>
</tr>

evaluacion/app/views/people/edit.html.erb
<h1>People#edit</h1>
<%= render 'form' %>

evaluacion/app/views/people/index.html.erb
<h1>Personas</h1>
<table class="table">
              <thead>
                  <tr>
                  <th scope="col">#</th><br>
                  <th scope="col">identificacion</th><br>
                  <th scope="col">primer nombre</th>
                  <th scope="col">segundo nombre</th>
                  <th scope="col">primer apellido</th>
                  <th scope="col">segundo apellido</th>
                  <th scope="col">tipo de documento</th>
                  <th scope="col">rol</th>
                  </tr>
              </thead>
              <tbody>
                <%= render @people%>
              </tbody>
              </table>

evaluacion/app/views/people/new.html.erb
<%= render 'form' %>

evaluacion/app/views/people/show.html.erb
<h1>Persona</h1>
<dl>
    <dt>Identificacion</dt>
    <dd><%=@person.identificacion%></dd>

    <dt>primer nombre</dt>
    <dd><%=@person.primer_nombre%></dd>

    <dt>segundo nombre</dt>
    <dd><%=@person.segundo_nombre%></dd>

    <dt>primer apellido</dt>
    <dd><%=@person.primer_apellido%></dd>

    <dt>segundo apellido</dt>
    <dd><%=@person.segundo_apellido%></dd>

    <dt>identificacion</dt>
    <dd><%=@person.document.tipo_documento%></dd>

    <dt>rol</dt>
    <dd><%=@person.role.nombre_rol%></dd>



    </dl>

    <%= link_to 'Editar', edit_person_path %> |
    <%= link_to 'Eliminar', @person, method: :delete %>